export const REQUEST_POLLS = 'REQUEST_POLLS';
export const RECEIVED_POLLS = 'RECEIVED_POLLS';

export const REQUEST_CREATE_POLL = 'CREATE_POLL_REQUEST';
export const ADD_POLL = 'ADD_POLL';

export const REQUEST_VOTE = 'REQUEST_VOTE';
export const RESPONSE_VOTE = 'RESPONSE_VOTE';

export const REQUEST_CREATE_OPTION = 'REQUEST_CREATE_OPTION';
export const ADD_OPTION = 'ADD_OPTION';

export const AUTH = {
  AUTH_SET_TOKEN: 'auth/SET_TOKEN',
  AUTH_DISCARD_TOKEN: 'auth/DISCARD_TOKEN',
  AUTH_SET_USER: 'auth/SET_USER',
  REQUEST_LOGIN: 'auth/REQUEST_LOGIN',
  CHECK_LOGIN: 'auth/CHECK_LOGIN',
};
